---
# Neural collapse config file. All must be specified
Model:
  model-name: resnet18            # Name of model in "Models.py"
  embedding-layers: [
    ^layer1.0.conv1,
    ^layer1.0.conv2,
    ^layer1.1.conv1,
    ^layer1.1.conv2,
    ^layer4.0.conv1,
    ^layer4.0.conv2,
    ^layer4.1.conv1,
    ^layer4.1.conv2,
    fc
    # ^layer1.0, ^layer1.1,
    # ^layer2.0, ^layer2.1,
    # ^layer3.0, ^layer3.1,
    # ^layer4.0, ^layer4.1,
    # ^avgpool, ^fc
  ]     # Intermediate layers to use for NC loss with weightings (True=>All layers/default)

Data:
  dataset-id: mnist      # Which dataset-getter to use. Note that shapes are provided by the dataset
  batch-size: 128        # Mini-batch size
  do-augmentation: False # Whether to do data augmentation

Optimizer:
  loss: mseloss
  weight-decay: 5.e-4    # Weight decay
  lr: 0.025              # Learning rate
  lr-decay: 0.2
  lr-decay-steps: 3      # Number of learning rate decay steps
  momentum: 0.9          # Optimizer momentum
  epochs: 0             # Number of epochs to train for

Logging:
  # When to store weights and calculate measurements
  save-dir: logs/debug
  # log-interval: 10        # At what interval to log checkpoints. Always includes first 10 epochs
  # log-epochs: [0, 1, 2, 3, 4, 5, 7, 10, 14, 20, 30, 40, 50, 60, 80, 100, 125, 150, 175, 200, 225, 250, 275, 300]  # Overrides log-interval
  log-epochs: [0]  # Overrides log-interval

Measurements:
  measures: [WeightSVs]
...
